### ISSUE TITLE
Expecting protobuf payloadpython

### ISSUE THREAD

**Issue by SivanLaai** [wxy1343/DepotDownloader#4]
python提示异常
详情如下：
```
python main.py app --app-path ./570940
Traceback (most recent call last):
  File "main.py", line 515, in <module>
    main()
  File "main.py", line 491, in main
    manifest_path_depot_key_dict = get_manifest_path_depot_key_dict(args.app_path)
  File "main.py", line 471, in get_manifest_path_depot_key_dict
    manifest = DepotManifest(content)
  File "/home/root/anaconda3/envs/python38/lib/python3.8/site-packages/steam/core/manifest.py", line 139, in __init__
    self.deserialize(data)
  File "/home/root/anaconda3/envs/python38/lib/python3.8/site-packages/steam/core/manifest.py", line 226, in deserialize
    raise Exception("Expecting protobuf payload")
Exception: Expecting protobuf payload
```
```
ll 570940
总用量 956K
-rw-rw-r-- 1 root root  944K 12月 15 11:09 570941_2900566705832487094.manifest
-rw-rw-r-- 1 root root    14 12月 15 11:09 570942_5866652778102292477.manifest
-rw-rw-r-- 1 root root  2.2K 12月 15 11:09 570943_2385633508013979570.manifest
-rw-rw-r-- 1 root root   316 12月 15 11:09 config.vdf
```

**Comment by wxy1343** [comment]
把文件发出来看看

**Comment by SivanLaai** [comment]
[570940.zip](https://github.com/wxy1343/DepotDownloader/files/13704112/570940.zip)

**Comment by wxy1343** [comment]
> [570940.zip](https://github.com/wxy1343/DepotDownloader/files/13704112/570940.zip)

![image](https://github.com/wxy1343/DepotDownloader/assets/49909001/e1c67195-0885-4be1-a590-40acaee957a5)

**Comment by SivanLaai** [comment]
ok，感谢
